import { StyleSheet } from "react-native";
import { sharedWorkspaceStyles } from "@/components/sharedWorkspaceStyles";

const ownStyles = StyleSheet.create({
  // Board Styles
  boardScrollContent: {
    paddingVertical: 20,
    paddingBottom: 48,
  },
  boardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  boardTitle: {
    fontSize: 24,
    fontFamily: "Inter_700Bold",
    letterSpacing: -0.6,
  },
  boardSubtitle: {
    marginTop: 4,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
  boardSettingsButton: {
    width: 42,
    height: 42,
    borderWidth: 1,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  boardError: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  boardErrorText: {
    flex: 1,
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 17,
  },
  boardSyncNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  boardSyncNoticeText: {
    flex: 1,
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 17,
  },
  boardSettings: {
    borderWidth: 1,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 18,
    padding: 14,
  },
  settingsSectionTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
  },
  settingsSectionHelp: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
    marginBottom: 10,
  },
  settingsRow: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderTopWidth: 1,
    paddingVertical: 7,
  },
  settingsNameInput: {
    flex: 1,
    minWidth: 80,
    minHeight: 38,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 7,
    fontFamily: "Inter_500Medium",
    fontSize: 13,
  },
  doneToggle: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 9,
  },
  doneToggleText: {
    fontFamily: "Inter_500Medium",
    fontSize: 11,
  },
  settingsAddRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
  },
  settingsAddInput: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 11,
    fontFamily: "Inter_400Regular",
    fontSize: 13,
  },
  settingsAddButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsDivider: {
    height: 1,
    marginVertical: 18,
  },
  fieldTypeBadge: {
    maxWidth: 74,
    fontFamily: "Inter_400Regular",
    fontSize: 10,
  },
  fieldTypePicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
  },
  fieldOptionsInput: {
    minHeight: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 8,
    fontFamily: "Inter_400Regular",
    fontSize: 12,
  },
  confirmPanel: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 11,
    marginBottom: 8,
  },
  confirmTitle: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 17,
  },
  confirmActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 16,
    marginTop: 11,
  },
  textButton: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    paddingVertical: 7,
  },
  destructiveButton: {
    minHeight: 38,
    borderRadius: 19,
    paddingHorizontal: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  destructiveButtonText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
  },
  choiceWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 8,
  },
  choiceChip: {
    minHeight: 36,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  choiceChipText: {
    fontFamily: "Inter_500Medium",
    fontSize: 11,
  },
  boardColumnsContainer: {
    paddingHorizontal: 16,
    gap: 12,
    alignItems: "flex-start",
  },
  boardColumn: {
    width: 286,
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
  },
  boardColumnHeader: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    paddingHorizontal: 3,
  },
  boardColumnTitleRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  boardColumnTitle: {
    flex: 1,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0,
  },
  boardColumnCount: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
  },
  boardColumnList: {
    gap: 8,
  },
  columnEmpty: {
    minHeight: 76,
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
  },
  columnEmptyText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    textAlign: "center",
  },
  columnAddButton: {
    minHeight: 42,
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  columnAddText: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
  },
  addTaskForm: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
  },
  addTaskInput: {
    minHeight: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginBottom: 10,
  },
  addTaskActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 14,
    alignItems: "center",
  },
  addTaskSubmit: {
    minHeight: 38,
    paddingHorizontal: 13,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  addTaskSubmitText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  kanbanCard: {
    borderWidth: 1,
    borderRadius: 10,
    overflow: "hidden",
  },
  kanbanCardMain: {
    padding: 11,
  },
  kanbanCardTitle: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    lineHeight: 19,
    marginBottom: 8,
  },
  cardFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 4,
  },
  cardFieldName: {
    flex: 1,
    fontFamily: "Inter_400Regular",
    fontSize: 10,
  },
  cardFieldValue: {
    maxWidth: "58%",
    fontFamily: "Inter_500Medium",
    fontSize: 10,
  },
  cardMoveActions: {
    height: 36,
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "rgba(127,127,127,0.18)",
    paddingHorizontal: 4,
  },
  cardMoveButton: {
    width: 34,
    height: 34,
    borderWidth: 2,
    borderColor: "transparent",
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  cardMoveSpacer: {
    flex: 1,
  },
  cardEditor: {
    width: "100%",
    maxWidth: 560,
    maxHeight: "92%",
    borderWidth: 1,
    borderRadius: 18,
    overflow: "hidden",
  },
  cardEditorContent: {
    padding: 18,
    paddingBottom: 12,
  },
  cardEditorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  cardEditorTitle: {
    fontFamily: "Inter_700Bold",
    fontSize: 20,
  },
  formLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    marginBottom: 7,
  },
  editorInput: {
    minHeight: 44,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 11,
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    marginBottom: 16,
  },
  editorField: {
    marginTop: 16,
  },
  checkboxField: {
    minHeight: 44,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  checkboxFieldText: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
  },
  editorError: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 14,
  },
  deleteCardButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    alignSelf: "flex-start",
    marginTop: 20,
  },
  deleteCardText: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
  },
  cardEditorFooter: {
    minHeight: 66,
    borderTopWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 14,
    paddingHorizontal: 18,
  },
  editorCancelButton: {
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  editorCancelText: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
  },
  editorSaveButton: {
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  editorSaveText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
  },
});

// Composed so existing `styles.<key>` references keep working for the few
// primitives every workspace shares.
export const styles = { ...sharedWorkspaceStyles, ...ownStyles };
