import { Platform, StyleSheet } from "react-native";
import { sharedWorkspaceStyles } from "@/components/sharedWorkspaceStyles";

/** Machine numbers in the dev goo HUD read in mono, per the design language. */
const slimeHudMonoFont = Platform.select({
  ios: "Menlo",
  android: "monospace",
  default: "monospace",
});

const ownStyles = StyleSheet.create({
  // Knowledge Styles
  knowledgeContainer: {
    flex: 1,
    position: "relative",
  },
  brainLayerRow: {
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  brainLayerRowContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingRight: 16,
  },
  brainLayerChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    maxWidth: 220,
  },
  brainLayerChipText: {
    fontSize: 12.5,
    fontFamily: "Inter_500Medium",
  },
  networkSuggestRow: {
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  networkSuggestLabel: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.3,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  networkSuggestRowContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingRight: 16,
  },
  networkSuggestChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderRadius: 999,
    paddingLeft: 10,
    paddingRight: 7,
    paddingVertical: 6,
  },
  networkSuggestApply: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    maxWidth: 190,
  },
  networkSuggestText: {
    fontSize: 12.5,
    fontFamily: "Inter_500Medium",
  },
  networkSuggestDismiss: {
    marginLeft: 2,
  },
  knowledgeCompanyProvenance: {
    fontSize: 12.5,
    lineHeight: 18,
    fontFamily: "Inter_500Medium",
    marginBottom: 12,
  },
  knowledgePromoteCard: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    marginBottom: 16,
    gap: 8,
  },
  knowledgePromoteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 6,
  },
  brainSearchWrap: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 6,
    position: "relative",
    zIndex: 40,
  },
  brainSearchField: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 40,
  },
  brainSearchInput: {
    flex: 1,
    fontSize: 14,
    paddingVertical: 0,
  },
  brainSearchResults: {
    position: "absolute",
    top: 54,
    left: 16,
    right: 16,
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 4,
    overflow: "hidden",
  },
  brainSearchList: {
    maxHeight: 288,
  },
  brainSearchEmpty: {
    fontSize: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  brainSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  brainSearchRowText: {
    flex: 1,
    minWidth: 0,
  },
  brainSearchRowLabel: {
    fontSize: 14,
    fontWeight: "600",
  },
  brainSearchRowMeta: {
    fontSize: 11,
    marginTop: 2,
  },
  brainSearchRowCount: {
    fontSize: 11,
    fontVariant: ["tabular-nums"],
  },
  knowledgeEmpty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 36,
  },
  knowledgeEmptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  knowledgeEmptyTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 18,
    textAlign: "center",
    marginBottom: 8,
  },
  knowledgeEmptyCopy: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    maxWidth: 340,
  },
  knowledgeCaptureButton: {
    position: "absolute",
    left: 16,
    bottom: 14,
    zIndex: 30,
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
  },
  symbioteStage: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
  },
  symbioteHud: {
    position: "absolute",
    top: 18,
    left: 16,
    right: 16,
    zIndex: 20,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  symbioteEyebrow: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0,
    marginBottom: 4,
  },
  symbioteTitle: {
    fontSize: 17,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: -0.35,
  },
  symbioteStatus: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderRadius: 15,
    paddingHorizontal: 10,
  },
  symbioteStatusDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
  },
  symbioteStatusText: {
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0,
  },
  symbioteViewport: {
    flex: 1,
    overflow: "hidden",
  },
  symbioteMap: {
    position: "absolute",
    width: 800,
    height: 800,
  },
  symbioteAura: {
    position: "absolute",
    width: 360,
    height: 360,
    borderRadius: 180,
    borderWidth: 1,
  },
  symbioteOrbit: {
    position: "absolute",
    width: 470,
    height: 470,
    borderRadius: 235,
    borderWidth: 1,
    opacity: 0.34,
    transform: [{ scaleY: 0.44 }, { rotate: "-8deg" }],
  },
  symbioteOrbitInner: {
    position: "absolute",
    width: 290,
    height: 290,
    borderRadius: 145,
    borderWidth: 1,
    opacity: 0.46,
    transform: [{ scaleY: 0.52 }, { rotate: "22deg" }],
  },
  tendrilSegment: {
    position: "absolute",
    overflow: "visible",
    borderWidth: 0.5,
    shadowOpacity: 0.32,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 4,
  },
  tendrilHighlight: {
    position: "absolute",
    left: 5,
    right: 5,
    top: 1,
    height: 1,
    borderRadius: 1,
    opacity: 0.36,
  },
  tendrilFlow: {
    position: "absolute",
    top: -2,
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  symbioteNodeMotion: {
    position: "absolute",
    zIndex: 10,
  },
  symbioteNodeHalo: {
    position: "absolute",
  },
  symbioteNode: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    overflow: "hidden",
  },
  symbioteNodeReflection: {
    position: "absolute",
    top: 7,
    right: 8,
    opacity: 0.7,
    transform: [{ rotate: "-16deg" }],
  },
  symbioteHint: {
    position: "absolute",
    bottom: 18,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  symbioteHintText: {
    fontSize: 11,
    fontFamily: "Inter_500Medium",
    letterSpacing: 0.2,
  },
  symbioteReset: {
    position: "absolute",
    right: 16,
    bottom: 14,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderRadius: 17,
    paddingHorizontal: 11,
  },
  // Dev-only goo performance HUD. Top-right under the status chip: the
  // bottom corners are taken (capture-note FAB left, reset right), and the
  // note FAB intercepts touches over anything sharing its corner.
  slimeHudToggle: {
    position: "absolute",
    right: 16,
    top: 56,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 17,
    paddingHorizontal: 11,
    zIndex: 30,
  },
  slimeHudToggleText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
  },
  slimeHudPanel: {
    position: "absolute",
    right: 16,
    top: 98,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
    zIndex: 30,
  },
  slimeHudRow: {
    fontSize: 11,
    fontFamily: slimeHudMonoFont,
    letterSpacing: 0,
  },
  symbioteResetText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
  },
  node: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  nodeLabelContainer: {
    position: "absolute",
    width: 150,
    alignItems: "center",
  },
  nodeLabel: {
    textAlign: "center",
    fontSize: 12,
  },
  knowledgeInfoPanel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    borderTopWidth: 1,
    paddingBottom: 34, // Safe area roughly
    maxHeight: "72%",
  },
  knowledgeInfoScroll: {
    flexShrink: 1,
  },
  knowledgeInfoContent: {
    padding: 20,
  },
  knowledgeInfoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  knowledgeInfoTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 18,
  },
  knowledgeInfoDesc: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 16,
  },
  knowledgeEditActions: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  knowledgeEditButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 7,
    minHeight: 44,
  },
  knowledgeEditButtonText: {
    fontSize: 12,
    fontFamily: "Inter_500Medium",
  },
  knowledgeEditCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  knowledgeEditLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
  },
  knowledgeEditHelp: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  knowledgeRenameInput: {
    borderWidth: 1,
    borderRadius: 8,
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  knowledgeEditError: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 6,
  },
  knowledgeEditCardActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 18,
    marginTop: 12,
  },
  knowledgeTextAction: {
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  knowledgeEditCancelText: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
  },
  knowledgeEditSaveText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
  },
  knowledgeRemoteMeta: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    marginBottom: 14,
  },
  knowledgeRemoteStatus: {
    alignItems: "center",
    gap: 10,
    paddingVertical: 26,
    paddingHorizontal: 12,
  },
  knowledgeRemoteStatusTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
  },
  knowledgeRemoteStatusCopy: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  knowledgeRemoteRetry: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginTop: 6,
    minHeight: 44,
  },
  knowledgeRemoteRetryText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
  },
  knowledgeRemoteBadges: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  knowledgeRemoteBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 5,
  },
  knowledgeRemoteBadgeText: {
    fontFamily: "Inter_500Medium",
    fontSize: 11,
  },
  knowledgeNeighborChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  knowledgeNeighborChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 36,
  },
  knowledgeNeighborChipText: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
  },
  knowledgeMergeOption: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    marginTop: 10,
    paddingTop: 10,
  },
  knowledgeMergeOptions: {
    maxHeight: 180,
  },
  knowledgeMergeOptionCopy: {
    flex: 1,
    paddingRight: 12,
  },
  knowledgeMergeOptionTitle: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
  },
  knowledgeMergeOptionMeta: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    marginTop: 2,
  },
  knowledgeDeleteConfirm: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  knowledgeInfoMeta: {
    flexDirection: "row",
    gap: 8,
  },
  metaBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  metaBadgeText: {
    fontSize: 12,
    fontFamily: "Inter_500Medium",
  },
  knowledgeSourcesLabel: {
    marginTop: 16,
    marginBottom: 6,
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    letterSpacing: 0,
  },
  knowledgeSourcesList: {
    flexShrink: 1,
  },
  knowledgeSourceRow: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    paddingVertical: 10,
  },
  knowledgeSourceCopy: {
    flex: 1,
    paddingRight: 12,
  },
  knowledgeSourceTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
  },
  knowledgeSourceExcerpt: {
    marginTop: 3,
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 17,
  },
  knowledgeConversationTranscript: {
    gap: 10,
  },
  knowledgeConversationMessage: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  knowledgeConversationSpeaker: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  knowledgeConversationBody: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 19,
  },
});

// Composed so existing `styles.<key>` references keep working for the few
// primitives every workspace shares.
export const styles = { ...sharedWorkspaceStyles, ...ownStyles };
